@Api_HostAddress = http://localhost:6008

### Obtener todos los cursos
GET {{Api_HostAddress}}/api/obtenercursos

### Obtener curso por año o division o todo junto
GET {{Api_HostAddress}}/api/obtenercurso/1-7

### Crear curso
POST {{Api_HostAddress}}/api/crearcurso
Content-Type: application/json
{
    "anio": "5",
    "division": "6-5-7-1",
    "idEscuela": "2",
    "idTurno": "1"
}

### Iniciar sesión
POST {{Api_HostAddress}}/api/login
Content-Type: application/json
{
    "emailUsername": "msmith@example.com",
    "password": "anotherPassword456"
}

### Obtener todas las escuelas
GET {{Api_HostAddress}}/api/obtenerescuelas

### Obtener escuela por nombre
GET {{Api_HostAddress}}/api/escuela?nombre=tin

### Obtener escuela
GET {{Api_HostAddress}}/api/escuela/martin

### Obtener todos los usuarios
GET {{Api_HostAddress}}/api/obtenerusuarios?id=1
