@Api_HostAddress = http://localhost:6008

### Obtener todos los cursos
GET {{Api_HostAddress}}/api/obtenercursos

POST {{Api_HostAddress}}/api/crearcurso
Content-Type: application/json
{
    "anio": "6",
    "division": "7-3-1-2-7-9-",
    "idEscuela": "2",
    "idTurno": "1"
}